# Generated by Django 3.1.1 on 2020-10-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='profile_pic',
        ),
    ]
